version: '3.9'

services:

    nginx-proxy:
        image: nginxproxy/nginx-proxy:alpine
        container_name: nginx-proxy
        restart: unless-stopped
        volumes:
            - ${DOCKER_SOCK_ROOTLESS_PATH:-/var/run/docker.sock}:/tmp/docker.sock:ro
            - ${NGINX_FILES_PATH:-./nginx}/conf.d:/etc/nginx/conf.d
            - ${NGINX_FILES_PATH:-./nginx}/vhost.d:/etc/nginx/vhost.d
            - ${NGINX_FILES_PATH:-./nginx}/html:/usr/share/nginx/html
            - ${NGINX_FILES_PATH:-./nginx}/certs:/etc/nginx/certs:ro
            - ${NGINX_FILES_PATH:-./nginx}/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - proxy

    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        restart: unless-stopped
        volumes:
            - ./database/data:/var/lib/mysql
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - sql

networks:

    proxy:
        driver: bridge
        name: docker_engine_proxy

    sql:
        driver: bridge
        name: docker_engine_sql