version: '3.7'

services:

    proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - "81:80" # change port if host nginx is running @floy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        networks:
            - proxy

    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        restart: unless-stopped
        volumes:
            - ./database/data:/var/lib/mysql
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - sql

    adminer:
        image: adminer:latest
        container_name: adminer
        environment:
            VIRTUAL_HOST: ${ADMINER_HOST}
            ADMINER_DEFAULT_SERVER: mysql
        networks:
            - frontend
            - sql

networks:
    proxy:
        driver: bridge
        name: docker_engine_proxy
    frontend:
        external:
            name: docker_engine_proxy
    sql:
        driver: bridge
        name: docker_engine_sql